[server]
# You can place other server configurations here

[theme]
base = "light"

# You can customize the colors further if you want, like:
# primaryColor = "#E694FF"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"
# font = "sans-serif"
